### PR TITLE
update instance type

### LINKED ISSUE #6: update instance type
https://github.com/moka-guys/dnanexus_verifybamid/blob/68e83c08b28a0349e0cb2cde9b34f9a6df781796/dxapp.json#L50

### PR DESCRIPTION
**Pull request by aledj2**
fix #6

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_verifybamid/7)

### CODE REVIEW

**Review by RachelDuffin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_verifybamid/7)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

*[a discussion](https://reviewable.io/reviews/moka-guys/dnanexus_verifybamid/7#-NRITsRH1MEtP4mtc6Aj:-NRITsRI0dwhFyaGE9KI:b-szvuw2) (no related file):*
Suggestion to remove the version number from the readme file - this is not needed as version can be seen by the tag / release, and adds another thing to remember to change which is unnecessary and can be easily missed / not noticed

___

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_verifybamid/7)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @aledj2)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_verifybamid/7)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @RachelDuffin)

*[a discussion](https://reviewable.io/reviews/moka-guys/dnanexus_verifybamid/7#-NRITsRH1MEtP4mtc6Aj:-NRIbdGRB_ZABdKiAu7B:b-896fix) (no related file):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Suggestion to remove the version number from the readme file - this is not needed as version can be seen by the tag / release, and adds another thing to remember to change which is unnecessary and can be easily missed / not noticed
</blockquote></details>

Done.

___

**Review by RachelDuffin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_verifybamid/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
